
# - name: Git clone
#   git:
#     repo: "{{ git_repo_netstats }}"
#     dest: "{{ git_dest_netstats }}"
#     update: yes
#     track_submodules: yes
#     accept_hostkey: yes
#     version: "{{ git_branch_netstats }}"

- name: Distribute unit file
  copy:
    src: ./config/dacc-stats.service
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Distribute ws-secret file
  template:
    src: ./config/ws_secret.json
    dest: "{{git_dest_netstats}}/ws_secret.json"
    owner: root
    group: root
    mode: '0644'  

- name: grunt
  environment:
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
  shell: grunt 
  args:
    chdir: "{{ git_dest_netstats }}"

- name: grunt all
  environment:
    PATH: /usr/local/go/bin:{{ ansible_env.PATH }}
  shell: grunt all
  args:
    chdir: "{{ git_dest_netstats }}"

- name: Restart dacc-stats service
  systemd:
    name: dacc-stats
    state: restarted
    daemon_reload: yes