
- name: Stop gdacc service
  systemd:
    name: gdacc
    state: stopped

- name: Rsync gdacc files
  synchronize: src={{git_dest}}/build/bin/gdacc dest=/opt/gdacc/bin
  delegate_to: dev

- name: Start gdacc service
  systemd:
    name: gdacc
    daemon_reload: yes
    state: started

- name: Set validator
  command: /opt/gdacc/bin/gdacc attach http://127.0.0.1:"{{ rpc_port }}" --exec "miner.setValidator(eth.accounts[0])"

- name: Unlock validator account
  command: /opt/gdacc/bin/gdacc attach http://127.0.0.1:"{{ rpc_port }}" --exec "personal.unlockAccount(eth.accounts[0], \"{{ validator_pwd }}\", 0)"

- name: Start miner
  command: /opt/gdacc/bin/gdacc attach http://127.0.0.1:"{{ rpc_port }}" --exec "miner.start(1)"