
- name: Build
  hosts: devserver
  remote_user: root
  roles:
    - build

- name: Rsyncdacc
  hosts: prodserver
  remote_user: root
  roles:
    - rsyncdacc   

- name: Deploy
  hosts: prodserver
  remote_user: root
  roles:
    - deploy