
- name: Build
  hosts: devserver
  remote_user: root
  roles:
    - build

- name: Init the Chain
  hosts: prodserver
  remote_user: root
  roles:
    - init


# #### deploy 
# - name: Build
#   hosts: devserver
#   remote_user: root
#   roles:
#     - build

# - name: Deploy the ChainCode 
#    hosts: prodserver
#    remote_user: root
#    roles:
#      - deploy     